### PR TITLE
WIP: porting to python3

### PR DESCRIPTION
**Pull request by josch**
since january 2020, python 2.7 is officially [dead and unmaintained](https://www.python.org/dev/peps/pep-0373/) Since the announcement of python's EOL 12 years have passed which should've been plenty of time to not start new python2 code or port existing py2 code to py3. Running python2 today is a security issue.

This pull request is a work-in-progress to move comma to python3. Lots of changes have been carried out already but there are still a few problems left (the test suite still has failing tests). The changes I made are enough for my use of comma, and csv-eval in particular. Maybe it is helpful for people who want to continue that work.

### CODE REVIEW

**Comment by vlaskine** [comment]
all the work for porting to python3 has been done long ago in the well-supported clone of comma/snark at https://gitlab.com/orthographic
regards

**Comment by josch** [comment]
Brilliant! Thanks! :)

Maybe this information could be mentioned in the README of this repository? Would've saved me some work. ^^

**Comment by josch** [comment]
Oh, and is this repository still maintained? Otherwise you could archive it in the settings to not confuse others as it confused me. :)

**Comment by vlaskine** [comment]
Hi,

I am not sure about http://github.com/acfr/comma: I don't have write access to it and whoever runs it in the Sydney University don't keep me in the loop on it.

I maintain http://gitlab.com/orthographic

My understanding is that you have your own fork of comma and snark? I am happy to 
accommodate small piecemeal pull requests, but not huge ones (my time is quite limited).

Also, http://gitlab.com/orthographic has got a lot of new functionality since it was forked year and half ago.

Cheers

**Pull request closed without merging**
